### ISSUE TITLE
Slow

### ISSUE THREAD

**Issue by DbomDev** [DbomDev/Serial-Generator#1]
I have noticed that it is slow and I am going to fix that Issue.

**Comment by David-Billingsley** [comment]
Hello,
   I am practicing a book called High Performance Python, and have been looking on GitHub for code samples.  I found yours and was wondering why do you have a sleep method.  This sleep call is adding about 1 minute and 50 seconds on average.  The JSON file write is the next highest time usage on my laptop. 

With Sleep:
Time ran -> 0:01:57.935337

Without Sleep:
Time ran -> 0:00:05.651106

**Comment by DbomDev** [comment]
Hey, Thanks for noticing me, I saw that now and corrected the script.
